export const CATEGORY_LABELS = {
  vegetable: '蔬菜区',
  meat: '肉类区',
};

export const DEFAULT_INGREDIENTS = [
  { id: 'veg_tomato', name: '番茄', category: 'vegetable', icon: '番', note: '酸甜开胃', isDefault: true, isHidden: false },
  { id: 'veg_cucumber', name: '黄瓜', category: 'vegetable', icon: '黄', note: '清爽脆口', isDefault: true, isHidden: false },
  { id: 'veg_potato', name: '土豆', category: 'vegetable', icon: '土', note: '百搭耐放', isDefault: true, isHidden: false },
  { id: 'veg_onion', name: '洋葱', category: 'vegetable', icon: '洋', note: '增香提味', isDefault: true, isHidden: false },
  { id: 'veg_broccoli', name: '西兰花', category: 'vegetable', icon: '西', note: '清炒常备', isDefault: true, isHidden: false },
  { id: 'meat_beef_brisket', name: '牛腩', category: 'meat', icon: '牛', note: '炖煮友好', isDefault: true, isHidden: false },
  { id: 'meat_chicken_wing', name: '鸡翅', category: 'meat', icon: '鸡', note: '烤煎都可', isDefault: true, isHidden: false },
  { id: 'meat_ribs', name: '排骨', category: 'meat', icon: '排', note: '红烧浓香', isDefault: true, isHidden: false },
  { id: 'meat_pork', name: '猪肉', category: 'meat', icon: '猪', note: '家常常用', isDefault: true, isHidden: false },
  { id: 'meat_beef_slice', name: '牛肉片', category: 'meat', icon: '片', note: '快炒省时', isDefault: true, isHidden: false },
];

export const RECIPES = [
  {
    id: 'recipe_candied_tomato',
    name: '糖渍番茄',
    category: '凉菜',
    summary: '三步完成的清甜小菜，适合夏天先垫垫肚子。',
    vegetables: ['番茄'],
    meats: [],
    otherIngredients: ['白糖'],
    seasonings: ['白糖', '少许盐'],
    steps: ['番茄切成月牙块。', '撒上白糖和一点点盐，拌匀静置 5 分钟。', '冷藏后食用口感更清爽。'],
    cookTime: 5,
    difficulty: '简单',
    tags: ['凉菜', '快手菜'],
  },
  {
    id: 'recipe_tomato_salad',
    name: '凉拌番茄',
    category: '凉菜',
    summary: '保留番茄本味，清爽不油腻。',
    vegetables: ['番茄'],
    meats: [],
    otherIngredients: ['香菜'],
    seasonings: ['生抽', '香醋', '少许糖'],
    steps: ['番茄切片装盘。', '把生抽、香醋和糖调成汁。', '浇在番茄上，点缀香菜即可。'],
    cookTime: 8,
    difficulty: '简单',
    tags: ['凉菜', '零失败'],
  },
  {
    id: 'recipe_smashed_cucumber',
    name: '拍黄瓜',
    category: '凉菜',
    summary: '爽脆开胃，十分钟内就能上桌。',
    vegetables: ['黄瓜'],
    meats: [],
    otherIngredients: ['蒜末'],
    seasonings: ['生抽', '香醋', '辣椒油', '盐'],
    steps: ['黄瓜拍裂后切段。', '蒜末和调味料混合成料汁。', '把料汁拌入黄瓜，静置入味。'],
    cookTime: 10,
    difficulty: '简单',
    tags: ['凉菜', '开胃'],
  },
  {
    id: 'recipe_tomato_cucumber_stir',
    name: '番茄炒黄瓜',
    category: '家常菜',
    summary: '酸甜清爽，适合晚饭快速出一盘蔬菜。',
    vegetables: ['番茄', '黄瓜'],
    meats: [],
    otherIngredients: ['蒜片'],
    seasonings: ['盐', '油', '糖'],
    steps: ['番茄切块，黄瓜切片。', '热锅下油煸香蒜片。', '先炒番茄再下黄瓜，调味翻匀即可。'],
    cookTime: 10,
    difficulty: '简单',
    tags: ['家常菜', '快手菜'],
  },
  {
    id: 'recipe_tomato_cucumber_onion_salad',
    name: '番茄黄瓜洋葱沙拉',
    category: '凉菜',
    summary: '口感层次丰富，适合做轻食配菜。',
    vegetables: ['番茄', '黄瓜', '洋葱'],
    meats: [],
    otherIngredients: ['柠檬汁'],
    seasonings: ['黑胡椒', '橄榄油', '盐'],
    steps: ['番茄、黄瓜、洋葱切小块。', '加入橄榄油、柠檬汁和调味料。', '轻轻翻拌后静置 3 分钟。'],
    cookTime: 8,
    difficulty: '简单',
    tags: ['轻食', '沙拉'],
  },
  {
    id: 'recipe_potato_onion_skillet',
    name: '洋葱土豆煎盘',
    category: '家常菜',
    summary: '表面焦香，适合当一餐里的主力配菜。',
    vegetables: ['土豆', '洋葱'],
    meats: [],
    otherIngredients: ['蒜末'],
    seasonings: ['黑胡椒', '盐', '油'],
    steps: ['土豆切薄片，洋葱切丝。', '平底锅铺油，先煎土豆至两面金黄。', '加入洋葱和蒜末翻炒，调味出锅。'],
    cookTime: 15,
    difficulty: '简单',
    tags: ['香煎', '家常'],
  },
  {
    id: 'recipe_broccoli_stir',
    name: '清炒西兰花',
    category: '家常菜',
    summary: '保留翠绿口感，适合搭配主菜。',
    vegetables: ['西兰花'],
    meats: [],
    otherIngredients: ['蒜末'],
    seasonings: ['盐', '蚝油'],
    steps: ['西兰花掰小朵焯水备用。', '热锅下油爆香蒜末。', '倒入西兰花翻炒，调味后出锅。'],
    cookTime: 10,
    difficulty: '简单',
    tags: ['家常菜', '清炒'],
  },
  {
    id: 'recipe_broccoli_onion_stir',
    name: '西兰花洋葱小炒',
    category: '家常菜',
    summary: '微甜带脆，做法简单稳定。',
    vegetables: ['西兰花', '洋葱'],
    meats: [],
    otherIngredients: ['蒜片'],
    seasonings: ['盐', '生抽', '油'],
    steps: ['西兰花焯水，洋葱切块。', '先炒香洋葱和蒜片。', '加入西兰花翻炒，淋少许生抽即可。'],
    cookTime: 12,
    difficulty: '简单',
    tags: ['家常菜', '快手菜'],
  },
  {
    id: 'recipe_red_braised_brisket',
    name: '红烧牛腩',
    category: '炖菜',
    summary: '酱香浓郁，适合想做一锅硬菜的时候。',
    vegetables: [],
    meats: ['牛腩'],
    otherIngredients: ['姜片', '八角'],
    seasonings: ['生抽', '老抽', '冰糖', '料酒'],
    steps: ['牛腩焯水后洗净。', '炒香冰糖、姜片和八角。', '加入牛腩和调味料炖煮至软烂。'],
    cookTime: 80,
    difficulty: '中等',
    tags: ['硬菜', '下饭'],
  },
  {
    id: 'recipe_tomato_brisket',
    name: '番茄牛腩',
    category: '炖菜',
    summary: '番茄的酸香能把牛腩味道托得更明亮。',
    vegetables: ['番茄'],
    meats: ['牛腩'],
    otherIngredients: ['姜片'],
    seasonings: ['盐', '番茄酱', '胡椒粉'],
    steps: ['牛腩焯水后备用，番茄切块。', '先把番茄炒出汁。', '加入牛腩和清水，小火炖至软烂。'],
    cookTime: 70,
    difficulty: '中等',
    tags: ['炖菜', '酸香'],
  },
  {
    id: 'recipe_potato_brisket',
    name: '土豆炖牛腩',
    category: '炖菜',
    summary: '土豆吸满汤汁，是非常稳妥的一锅菜。',
    vegetables: ['土豆'],
    meats: ['牛腩'],
    otherIngredients: ['姜片', '葱段'],
    seasonings: ['生抽', '老抽', '盐'],
    steps: ['牛腩先炖 40 分钟。', '放入土豆块继续炖煮。', '收汁到土豆绵软即可。'],
    cookTime: 75,
    difficulty: '中等',
    tags: ['炖菜', '家常'],
  },
  {
    id: 'recipe_beef_slice_cucumber',
    name: '黄瓜拌牛肉片',
    category: '凉拌热菜',
    summary: '牛肉片和黄瓜一冷一热，吃起来很解腻。',
    vegetables: ['黄瓜'],
    meats: ['牛肉片'],
    otherIngredients: ['蒜末'],
    seasonings: ['生抽', '香醋', '香油'],
    steps: ['牛肉片焯熟备用。', '黄瓜切条，用少许盐抓匀。', '把牛肉和黄瓜拌匀，加入调味料即可。'],
    cookTime: 12,
    difficulty: '简单',
    tags: ['凉拌', '快手'],
  },
  {
    id: 'recipe_pork_onion_stir',
    name: '洋葱炒猪肉',
    category: '家常菜',
    summary: '洋葱自带甜味，很适合做快炒主菜。',
    vegetables: ['洋葱'],
    meats: ['猪肉'],
    otherIngredients: ['青椒'],
    seasonings: ['生抽', '料酒', '盐'],
    steps: ['猪肉切片提前腌 10 分钟。', '热锅先炒猪肉至变色。', '加入洋葱和青椒快速翻炒调味。'],
    cookTime: 15,
    difficulty: '简单',
    tags: ['快炒', '下饭'],
  },
  {
    id: 'recipe_ribs_potato',
    name: '土豆烧排骨',
    category: '炖烧',
    summary: '汤汁浓稠、很适合配米饭。',
    vegetables: ['土豆'],
    meats: ['排骨'],
    otherIngredients: ['姜片'],
    seasonings: ['生抽', '老抽', '冰糖', '盐'],
    steps: ['排骨焯水后下锅炒香。', '加入调味料和清水炖煮。', '放入土豆继续烧至入味收汁。'],
    cookTime: 55,
    difficulty: '中等',
    tags: ['炖烧', '硬菜'],
  },
  {
    id: 'recipe_cola_wings',
    name: '可乐鸡翅',
    category: '家常菜',
    summary: '新手也比较容易成功的甜咸口主菜。',
    vegetables: [],
    meats: ['鸡翅'],
    otherIngredients: ['姜片'],
    seasonings: ['可乐', '生抽', '盐'],
    steps: ['鸡翅煎至两面微黄。', '加入可乐和生抽没过鸡翅。', '中火收汁，最后略微翻亮。'],
    cookTime: 25,
    difficulty: '简单',
    tags: ['新手友好', '甜咸口'],
  },
  {
    id: 'recipe_broccoli_beef_slice',
    name: '西兰花炒牛肉片',
    category: '家常菜',
    summary: '高频工作日晚餐搭配，清爽又有饱腹感。',
    vegetables: ['西兰花'],
    meats: ['牛肉片'],
    otherIngredients: ['蒜片'],
    seasonings: ['蚝油', '黑胡椒', '盐'],
    steps: ['牛肉片用蚝油和胡椒简单抓匀。', '西兰花焯水备用。', '先滑炒牛肉，再合炒西兰花调味。'],
    cookTime: 15,
    difficulty: '简单',
    tags: ['快炒', '工作日晚餐'],
  },
];
